### ISSUE TITLE
Implement support for external interrupts

### ISSUE THREAD

**Issue by danicampora** [danicampora/micropython#12]

**Comment by dpgeorge** [comment]
Please consider following stmhal's API for this (ExtInt class).  Even better would be to somehow make stmhal/extint.c reusable for this port by abstracting the external interrupt hardware implementation.  This also goes for the other classes (UART, SPI, I2C, etc).  Some may be difficult to do, so let's see how it goes.

**Comment by danicampora** [comment]
Ok, I will follow the path you suggest, lets see where it takes me...

**Comment by danicampora** [comment]
@dpgeorge I know that you are super busy, but I just one to know if the stack usage that I have seen is normal...

**Comment by dpgeorge** [comment]
You need about 216 bytes stack for a Python function call.  You can check using micropython.mem_info() function (it tells current stack usage).  But for an IRQ call it depends how much extra overhead you have setting up the callback.  Try printing the result of mp_stack_usage() in different places in the IRQ to see how much stack you are using (actually this won't work because mp_stack_usage measures for the main thread and you'll be on the IRQ stack... so you'll need to write your own version of mp_stack_usage for the IRQ; should be easy).

**Comment by danicampora** [comment]
Thanks!. I already have something in place to check the high water mark of the main stack. But that info about the 216 bytes is what I was looking for.
